# Generated by Django 4.1.3 on 2022-11-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedades',
                'ordering': ['name'],
            },
        ),
    ]
