# Generated by Django 4.1.3 on 2022-11-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_comfort'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='confort',
            field=models.ManyToManyField(blank=True, null=True, to='rentals.comfort'),
        ),
    ]
