# Generated by Django 4.1.3 on 2022-11-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_property_confort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='confort',
            field=models.ManyToManyField(blank=True, to='rentals.comfort'),
        ),
    ]
