# Generated by Django 4.1.3 on 2022-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_property_confort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('option_choises', models.IntegerField(choices=[['1', 'CONSULTA'], ['2', 'RECLAMO'], ['3', 'SUGERENCIA'], ['4', 'FELICITACIONES']])),
                ('mensaje', models.TextField(max_length=500)),
                ('avisos', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
    ]
