# Generated by Django 4.1.3 on 2022-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_contact_option_choises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='option_choises',
            field=models.IntegerField(choices=[('0', 'CONSULTA'), ('1', 'RECLAMO'), ('2', 'SUGERENCIA'), ('3', 'FELICITACIONES')], default='0'),
        ),
    ]
