# Generated by Django 4.1.3 on 2022-11-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_contact_option_choises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='option_choises',
        ),
    ]
